language: php

sudo: required
dist: trusty
php:
  - 7.3

services:
  - mysql
  - memcached

git:
  depth: 1

cache:
  apt: true
  ccache: true
  timeout: 691200
  directories:
    - .temp
    - $HOME/.ccache
    - $HOME/.composer/cache

env:
  global:
    - ZEND_DONT_UNLOAD_MODULES=1
    - CC="ccache gcc"
    - PATH="$PATH:~/bin"
    - DISPLAY=":99.0"
    - APPLICATION_ENV=testing
  matrix:
    - PHALCON_VERSION="v4.0.3"


before_install:
  - export PHP_MAJOR="$(echo $TRAVIS_PHP_VERSION | cut -d '.' -f 1,2)"
  - sudo ln -s /home/travis/.phpenv/versions/$(phpenv version-name)/bin/phpize /usr/bin/
  - sudo ln -s /home/travis/.phpenv/versions/$(phpenv version-name)/bin/php-config /usr/bin/
  - phpenv config-rm xdebug.ini || true
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - travis_retry composer install --prefer-dist --no-interaction --ignore-platform-reqs
  - travis_retry composer require --dev "phalcon/zephir:0.9.11" --ignore-platform-reqs
  - ( bash tests/_ci/install_zephir.sh )
  - bash tests/_ci/install_prereqs_$PHP_MAJOR.sh

install:
  - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b ${PHALCON_VERSION}
  - '( cd cphalcon; zephir fullclean && zephir generate $ZEND_BACKEND )'
  - (cd cphalcon/ext; export CFLAGS="-g3 -O1 -std=gnu90 -Wall -DZEPHIR_RELEASE=1"; /usr/bin/phpize &> /dev/null && ./configure --silent --enable-phalcon &> /dev/null && make --silent -j2 &> /dev/null && make --silent install)
  - phpenv config-add cphalcon/tests/_ci/phalcon.ini

before_script:
  - echo 'CREATE DATABASE phalcms CHARSET=utf8 COLLATE=utf8mb4_unicode_ci' | mysql -u root
  - cat src/install.sql | mysql -uroot phanbook
  - cp ./tests/.env.travis .env
  - php -S 127.0.0.1:8000 -t public/ .htrouter.php >/dev/null 2>&1 &
  - ulimit -c unlimited -S || true

script:
  - vendor/bin/phpcs --extensions=php
  - vendor/bin/codecept build
  - vendor/bin/codecept run

notifications:
  email:
    recipients:
      - info@clsystems.nl
    on_success: change
    on_failure: always

addons:
  apt:
    packages:
      - gdb
      - re2c
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
  hosts:
    - db
    - phanbook.dev
