language: php

sudo: false

matrix:
  include:
    - php: 7.2

before_install: composer self-update

install: composer install

before_script:
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --log-junit build/logs/phpunit.xml